### ISSUE TITLE
CPS optimization problems involving set and primitives that work with immutable data

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#172] opened 2017-02-06 05:09 UTC
If you compile [the file in here](https://github.com/justinethier/cyclone/files/753674/demonstration.zip) and execute the result, Cyclone explodes with the following error:

```
Error: vector-ref - invalid index: -1 
Call history:
scheme/base.sld:foldr
test.scm:any
scheme/base.sld:list
scheme/base.sld:append
scheme/base.sld:foldl
scheme/base.sld:foldr
scheme/base.sld:foldl
scheme/base.sld:map
scheme/base.sld:foldr
```
If you run the same file with Chibi, it correctly displays ``(5 4 3 2 1)``. I've provided the bare minimum required to replicate this behaviour - this is from the reference implementation of SRFI 121. I'm not sure what the cause is, but this is currently the only thing blocking a PR for this by me.

**Comment by justinethier** [comment] 2017-02-06 22:02
Thanks for reporting this. The problem is the optimizer is being too eager and has reorganized the code such that the subtractions are occurring in the opposite order, leading to a calculation of -1 instead of 0. You can see the program works fine if optimizations are disabled:

    cyclone -O0 test.scm

Let me look under the hood a bit and figure out a proper solution.

**Comment by justinethier** [comment] 2017-02-07 20:05
The problem here is that `prim-calls-inlinable?` is being allowed to inline certain calls if their arguments and results are immutable. Unfortunately this short-circuits other code that is performing a more detailed analysis to determine if a particular inline is allowed, or if it will cause problems such as out-of-order execution (which is a concern when mutations are involved).

The simple fix is to just remove this call, which fixes the problem but unfortunately makes other code a bit slower. A better fix would be to do that and also see if we could make the inline check a bit more sophisticated to compensate.

**Comment by kozross** [comment] 2017-02-07 20:38
It is my belief that correctness must come first; getting the wrong answer, even quickly, is definitely not a desirable thing. I would suggest removing the call for now - I don't have enough knowledge of Cyclone's internals to contribute a better fix myself, and you seem to have your hands full with other things - and leave this issue open for future work direction.

**Comment by justinethier** [comment] 2017-02-08 01:52
Agreed, this line has been removed and all of the scheme files have been recompiled. I just hate giving up performance unless it is absolutely necessary because it can be so hard to reclaim. This is a good example of a case where we need to, though. At least for now.

**Comment by kozross** [comment] 2017-02-08 06:57
Yeah, it's definitely something that'll need revisiting. However, you seem to have your hands full at the moment.

**Comment by justinethier** [comment] 2017-05-17 21:02
The optimization technique originally used here was flawed. Closing.

**Closed by justinethier** 2017-05-17 21:02 UTC
